apiVersion: v1
kind: Service
metadata:
  name: redis-service  #{{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
      protocol: TCP
      name: redis-port
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
    component: redis-pod
